firmware:
  image: antoinealb/gcc-arm-embedded
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install cvra-packager
    - git submodule update --init
    - packager
    - make

bootloader:
  image: antoinealb/gcc-arm-embedded
  script:
    - git submodule update --init
    - cd aseba-bootloader
    - pushd libopencm3 && make && popd
    - make
