dependency-dir: src/

depends:
    - parameter
    - crc

source:
    - src/config_flash_storage.c

tests:
    - tests/config_save_test.cpp
    - tests/flash_mock.cpp

target.arm:
    - src/panic.c
    - src/cmd.c
    - src/main.c
    - src/usbcfg.c
    - src/malloc_lock.c
    - src/memory_protection.c
    - src/flash/flash.c
    - src/discovery_demo/leds.c
    - src/discovery_demo/accelerometer.c
    - src/discovery_demo/button.c


templates:
    src/src.mk.jinja: src/src.mk
